server:
  port: 8080
  readtimeout: 60
  writetimeout: 60
  maxHeaderBytes: 60
  runmode: debug
datasource:
  driver: mysql
  userName: root
  password: admin
  schema: blog
  addr: 127.0.0.1:3306
  charSet: utf8
  parseTime: true
  loc: local
  maxidleconns: 10
  maxopenconns: 30