server:
  port: 8080
  readtimeout: 60
  writetimeout: 60
  maxHeaderBytes: 60
  runmode: release
  logger:
    level: debug
    path:  storage/logger
    file:  blog.logger
datasource:
  driver: mysql
  userName: root
  password: admin
  schema: blog.text
  addr: 127.0.0.1:3306
  charSet: utf8
  parseTime: true
  loc: local
  maxidleconns: 10
  maxopenconns: 30